# .readthedocs.yaml
# Read the Docs Configuration file


# Required
version: 2

submodules:
  include: all

# Set the tools
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt-packages:
    - cmake
    - doxygen

sphinx:
  configuration: docs/conf.py


# Optionally declare the Python requirements required to build your docs
python:
  install:
   - requirements: doc/requirements.txt
  system_packages: true
